### ISSUE TITLE
Organization or Currency should be hidden

### ISSUE THREAD

**Issue by skarampatakis** [openbudgets/integration#10]
There is no meaning of having these on the hierarchies list from my point of view.
![image](https://user-images.githubusercontent.com/2419820/28656111-b18a538a-72a8-11e7-9892-5c5845670ece.png)

**Comment by larjohn** [comment]
If you mean the dimensions with a single value, this has been discussed and decided about a year ago..

**Comment by skarampatakis** [comment]
I do not recall such conversation or found any issue, but whatever...

**Comment by larjohn** [comment]
https://github.com/openspending/openspending/issues/1055

**Comment by skarampatakis** [comment]
I understand the posted issue as a completely different issue, but as I said it is a matter of perspective. If you think it is OK to be as is, let it be that way.

**Comment by larjohn** [comment]
In order to resolve this issue we had aggreed to include all dataset-level dimensions in the results. This is a bit wrong perspective, but the alternative would be to hardcode the time dimension just for the viewer.
