### ISSUE TITLE
OpenSpending OS Viewer shows dimension's code instead of label

### ISSUE THREAD

**Issue by fathoni** [openbudgets/integration#12]
OpenSpending OS Viewer shows code instead of label in treemap visualization. See [here](https://next.openspending.org/viewer/848b8e447d0dfc798a77ef4f3a7bbcbd:bonn-simplified-2017?measure=%22Plan2017.sum%22&groups%5B%5D=%22functional_classification_2.Produktbereich%22&order=%22Plan2017.sum%7Cdesc%22&visualizations%5B%5D=%22Treemap%22&lang=en) for example.

**Comment by larjohn** [comment]
Look here:

https://openspending.org/api/3/cubes/848b8e447d0dfc798a77ef4f3a7bbcbd:bonn-simplified-2017/model


The label and the key properties both point to the same attribute. This is a data modelling issue, probably introduced when the dataset was uploaded. I am not familiar with the process, maybe someone else can help here.

**Comment by skarampatakis** [comment]
@fathoni Is this still an issue on OBEU server?

**Comment by fathoni** [comment]
The proper label has appeared in the OBEU server.
