### ISSUE TITLE
10k limit on Virtuoso

### ISSUE THREAD

**Issue by larjohn** [openbudgets/integration#14]
While most of the datasets are only a couple of thousands rows big, there are the Bonn datasets that go over 10k maxing the Virtuoso configuration out.

Would you suggest to change the setting and provide the whole dataset link to the DAM app or keep the limit and paginate  in DAM?

**Comment by liyakun** [comment]
@larjohn sorry for the late in replying. I think it is okay to change the limit on the server currently if it is easier for your side, how do you think?

**Comment by liyakun** [comment]
@larjohn For a long term, I think it is better to do this in DAM, as there is not always a max limit in real dataset but there is limitation in the hard and software on the server.

**Comment by larjohn** [comment]
I agree

**Comment by liyakun** [comment]
@larjohn I already adapted the upper limit in triple store, it should be fine now.
