### ISSUE TITLE
Alignment Github callback

### ISSUE THREAD

**Issue by skarampatakis** [openbudgets/integration#20]
@liyakun 
There may be a misconfiguration on Github for the Alignment callback. Can you check this?

After I succesfully grant access, I get a redirect to 
```
https://alignment-obeu.iais.fraunhofer.de/auth/github/callback?error=redirect_uri_mismatch&error_description=The%2Bredirect_uri%2BMUST%2Bmatch%2Bthe%2Bregistered%2Bcallback%2BURL%2Bfor%2Bthis%2Bapplication.&error_uri=https%3A%2F%2Fdeveloper.github.com%2Fv3%2Foauth%2F%23redirect-uri-mismatch&state=N50MDpshkjSn0TR9XkXhebBHEGXgy9e4PffBEWKF
```

which is the wrong link.

**Comment by liyakun** [comment]
@skarampatakis I checked on the server, if i am correct, this is setted in [.env](https://github.com/openbudgets/integration/blob/master/docker-config/alignment/.env), on the server, it is same as in github.

**Comment by skarampatakis** [comment]
Yes you are correct. On the .env it is configured correctly. But is this the same on Github. Or maybe it is related with some caching on my client?

**Comment by skarampatakis** [comment]
This is a part from the response header
```
HTTP/1.1 302 Found
Server: GitHub.com
Date: Mon, 18 Sep 2017 11:31:48 GMT
Content-Type: text/html; charset=utf-8
Transfer-Encoding: chunked
Status: 302 Found
Cache-Control: no-cache
Vary: X-PJAX
Location: https://alignment-obeu.iais.fraunhofer.de/auth/github/callback?error=redirect_uri_mismatch&error_description=The+redirect_uri+MUST+match+the+registered+callback+URL+for+this+application.&error_uri=https%3A%2F%2Fdeveloper.github.com%2Fv3%2Foauth%2F%23redirect-uri-mismatch&state=wXAL9xIrrTy1NocpvfgbwO9sYb2vqyZTWqQP8SxC
X-UA-Compatible: IE=Edge,chrome=1
```

**Comment by liyakun** [comment]
@skarampatakis thanks, adapted Github callback, it should work now.

**Comment by liyakun** [comment]
@skarampatakis I think it is better to use https ranther than http for auth, so I changed the call back to be https, how do you think?

**Comment by skarampatakis** [comment]
I strongly agree but I don't know how to set it up with nginx and stuff. If you can handle it I have no objection.

**Comment by liyakun** [comment]
@skarampatakis okay, great, I think we can allow user only use https, which is https://apps.openbudgets.eu/alignment/, I already configured https for alignment on nginx, it should be fine.

**Comment by skarampatakis** [comment]
I have seen that you have already done this. Great! But I cannot create a new project on the App and have no access on the logs. Perhaps we should also mount the logs folder. It is on /var/www/alignment/storage/logs

**Comment by liyakun** [comment]
@skarampatakis  i will mount the logs folder to alignment.

**Comment by skarampatakis** [comment]
I see no errors on the logs. That probably means that it has no rights to write on the logs file. I will update the Dockerfile.

**Comment by liyakun** [comment]
@skarampatakis before merge your changes to prod.yml of the logs, i mount the one at /volumes/alignment/logs to container, there are also two files on this folder, maybe it is helpful for you.

**Comment by skarampatakis** [comment]
Can you try to refresh now? I still get not clue of what is happening. It should throw an error at least.

**Comment by skarampatakis** [comment]
I have changed the listener user as I think this is the problem. Listener was running as root so every file it generates has owner the root. Please pull and refresh.

**Comment by liyakun** [comment]
@skarampatakis alreay refreshed on the server.

**Comment by skarampatakis** [comment]
It is working when I test locally. I don't know what is happening on the server. Please remove alignment volumes completely and rerun the initVolumes.sh script to set the correct permissions, and then refresh the server again. Perhaps removing cache items from the alignment image could fix this. 

However the original issue is resolved so I think we could close this issue. Please inform when you have the server updated in order to check. I will try to provide some unit tests also to avoid such issues.

**Comment by liyakun** [comment]
@skarampatakis I changed the access right to the shared folders by alignment, could you check again? I don't know what error you are trying to see, could you tell?

**Comment by skarampatakis** [comment]
Please check #21.
