### ISSUE TITLE
Alignment: Similarity Calculation Job fails to start

### ISSUE THREAD

**Issue by skarampatakis** [openbudgets/integration#21]
It seems that the supervisor has some error and is not running. When I click on "Calculate similarities" button on the projects page, the configuration is created but then nothing happens. This is due to supervisor is not running.

**Comment by liyakun** [comment]
@skarampatakis I was updating the alignment docker, could you check again?

**Comment by skarampatakis** [comment]
OK. Now it seems to be working as supposed. Thank you!
