### ISSUE TITLE
RDFBrowser delivers no output

### ISSUE THREAD

**Issue by seegerseeger** [openbudgets/integration#23]
http://data.openbudgets.eu/ contains two links:

http://0.0.0.0/RDFBrowser/browse/1
http://0.0.0.0/RDFBrowser/browse/2

Both URLs deliver empty outputs. Is this an issue with URL? 
@larjohn @skarampatakis

**Comment by skarampatakis** [comment]
This has been fixed on the latest update as seen on #22. 

A refresh on the server is required however.

**Comment by skarampatakis** [comment]
For instance, that is what should be expected 

http://data.openbudgets.eu/browse/1

**Comment by skarampatakis** [comment]
Fixed by the latest update.
