### ISSUE TITLE
Reduce LP instances on prod.yml

### ISSUE THREAD

**Issue by skarampatakis** [openbudgets/integration#25]
Atm there are 5 LP instances. I think we can reduce the footprint by having just 2, one for the FDP2RDF pipeline and one for custom pipelines.

**Comment by skarampatakis** [comment]
@liyakun Any progress or decision on this?

**Comment by liyakun** [comment]
@skarampatakis I have not work on this, but you are right, it is better to remove some of them. I will work on this asap.

**Comment by skarampatakis** [comment]
Great. Please close this when ready.

**Comment by liyakun** [comment]
Done.
