### ISSUE TITLE
RDF-utils Failure

### ISSUE THREAD

**Issue by VonNao** [openbudgets/integration#27]
Hello everybody,

i got a problem with the rdf-utils plugin during linkedpipes.etl.rdf.utils.RdfBuilderTest

At the start of the reactor summary the rdf-utils gets a failure status and the whole maven deployment ends with the "Builf failure" message. 

`[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.20.1:test (default-test) on project rdf-utils: There are test failures.
[ERROR]
[ERROR] Please refer to /etl/rdf-utils/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date]-jvmRun[N].dump, [date].dumpstream and [date]-jvmRun[N].dumpstream.
[ERROR] The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was /bin/sh -c cd /etl/rdf-utils && /usr/lib/jvm/java-1.8-openjdk/jre/bin/java -jar /etl/rdf-utils/target/surefire/surefirebooter5044536894785048322.jar /etl/rdf-utils/target/surefire 2017-09-25T14-12-25_924-jvmRun1 surefire5772724010396559587tmp surefire_0148726905675929990tmp
[ERROR] Error occurred in starting fork, check output in log
[ERROR] Process Exit Code: 1
[ERROR] Crashed tests:
[ERROR] com.linkedpipes.etl.rdf.utils.RdfBuilderTest
[ERROR] org.apache.maven.surefire.booter.SurefireBooterForkException: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was /bin/sh -c cd /etl/rdf-utils && /usr/lib/jvm/java-1.8-openjdk/jre/bin/java -jar /etl/rdf-utils/target/surefire/surefirebooter5044536894785048322.jar /etl/rdf-utils/target/surefire 2017-09-25T14-12-25_924-jvmRun1 surefire5772724010396559587tmp surefire_0148726905675929990tmp
[ERROR] Error occurred in starting fork, check output in log
[ERROR] Process Exit Code: 1
[ERROR] Crashed tests:
[ERROR] com.linkedpipes.etl.rdf.utils.RdfBuilderTest
[ERROR] at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:686)
[ERROR] at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:535)
[ERROR] at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:280)
[ERROR] at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:245)
[ERROR] at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1124)
[ERROR] at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:954)
[ERROR] at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:832)
[ERROR] at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
[ERROR] at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
[ERROR] at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
[ERROR] at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
[ERROR] at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
[ERROR] at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
[ERROR] at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
[ERROR] at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
[ERROR] at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
[ERROR] at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
[ERROR] at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
[ERROR] at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
[ERROR] at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
[ERROR] at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
[ERROR] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR] at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR] at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR] at java.lang.reflect.Method.invoke(Method.java:498)
[ERROR] at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
[ERROR] at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
[ERROR] at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
[ERROR] at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[ERROR] -> [Help 1]
`

 Is this a failure on my end?  Am i missing something important?

Thank you very much for your help!

Best regards 
VonNao

**Comment by liyakun** [comment]
@VonNao I am not clear about how you trigger `inkedpipes.etl.rdf.utils.RdfBuilderTest`, could you provide more information about how thoese errors are triggered? thanks and sorry for delay in replying.

@fathoni Could you have a look at this issue? thanks.

**Comment by VonNao** [comment]
Hello @liyakun ,
hello @fathoni ,

 
thank you for your help.
 
We cloned the github repository to our local CentOS system which runs docker and docker-compose. 
After that we started creating the needed directories/volumes with the script „initVolumes.sh“ which was included in the repository. 
 
This part worked without any problem. 
In the next step we renamed the env.example file to .env so that the „refresh_and_restart_prod.sh“ script would work. 
 
During the script the following error occurred.
 
[INFO]
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running com.linkedpipes.etl.rdf.utils.RdfBuilderTest
[INFO]
[INFO] Results:
[INFO]
[INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] lp-pom-parent ...................................... SUCCESS [  0.314 s]
[INFO] lp-pom-component ................................... SUCCESS [  0.003 s]
[INFO] lp-vocabulary ...................................... SUCCESS [  2.685 s]
[INFO] rdf-utils .......................................... FAILURE [  3.468 s]
[INFO] rdf-utils-rdf4j .................................... SKIPPED
[INFO] lp-api-executor-v1 ................................. SKIPPED
[INFO] lp-dataunit-core ................................... SKIPPED
[INFO] lp-executor ........................................ SKIPPED
[INFO] lp-executor-monitor ................................ SKIPPED
[INFO] lp-storage ......................................... SKIPPED
[INFO] lp-test-environment ................................ SKIPPED
[INFO] plugin t-chunkedToGraph ............................ SKIPPED
[INFO] plugin t-excelToCsv ................................ SKIPPED
[INFO] plugin t-filesFilter ............................... SKIPPED
[INFO] plugin l-filesToScp ................................ SKIPPED
[INFO] plugin e-datasetMetadata ........................... SKIPPED
[INFO] plugin e-dcatAp11Dataset ........................... SKIPPED
[INFO] plugin e-distributionMetadata ...................... SKIPPED
[INFO] plugin e-dcatAp11Distribution ...................... SKIPPED
[INFO] plugin e-voidDataset ............................... SKIPPED
[INFO] plugin l-dcatAp11ToCkan ............................ SKIPPED
[INFO] plugin l-lodCloud .................................. SKIPPED
[INFO] plugin t-filesToRdf ................................ SKIPPED
[INFO] plugin t-filesToRdfChunked ......................... SKIPPED
[INFO] plugin t-filesToRdfGraph ........................... SKIPPED
[INFO] plugin t-filesToStatements ......................... SKIPPED
[INFO] plugin t-graphMerger ............................... SKIPPED
[INFO] plugin t-packZip ................................... SKIPPED
[INFO] plugin t-rdfToFile ................................. SKIPPED
[INFO] plugin t-rdfToFileChunked .......................... SKIPPED
[INFO] plugin t-sparqlConstruct ........................... SKIPPED
[INFO] plugin t-sparqlConstructChunked .................... SKIPPED
[INFO] plugin t-sparqlLinkerChunked ....................... SKIPPED
[INFO] plugin t-sparqlSelect .............................. SKIPPED
[INFO] plugin t-sparqlUpdate .............................. SKIPPED
[INFO] plugin t-sparqlUpdateChunked ....................... SKIPPED
[INFO] plugin t-tabular ................................... SKIPPED
[INFO] plugin t-tabularChunked ............................ SKIPPED
[INFO] plugin t-unpack .................................... SKIPPED
[INFO] plugin t-unpackZip ................................. SKIPPED
[INFO] plugin t-xslt ...................................... SKIPPED
[INFO] plugin x-virtuoso .................................. SKIPPED
[INFO] plugin e-httpGetFile ............................... SKIPPED
[INFO] plugin e-sparqlEndpoint ............................ SKIPPED
[INFO] plugin e-sparqlEndpointChunked ..................... SKIPPED
[INFO] plugin e-sparqlEndpointSelect ...................... SKIPPED
[INFO] plugin e-sparqlEndpointSelectScrollableCursor ...... SKIPPED
[INFO] plugin e-sparqlEndpointConstructScrollableCursor ... SKIPPED
[INFO] plugin e-textHolder ................................ SKIPPED
[INFO] plugin l-dcatApToCkan .............................. SKIPPED
[INFO] plugin l-graphStoreProtocol ........................ SKIPPED
[INFO] plugin l-sparqlEndpoint ............................ SKIPPED
[INFO] plugin t-filesBase64Decode ......................... SKIPPED
[INFO] plugin t-mustache .................................. SKIPPED
[INFO] plugin q-sparqlAsk ................................. SKIPPED
[INFO] plugin l-filesToLocal .............................. SKIPPED
[INFO] plugin e-ftpFiles .................................. SKIPPED
[INFO] plugin l-ftpFiles .................................. SKIPPED
[INFO] plugin e-filesFromLocal ............................ SKIPPED
[INFO] plugin t-tabularUv ................................. SKIPPED
[INFO] plugin t-singleGraphUnion .......................... SKIPPED
[INFO] plugin e-httpGetFiles .............................. SKIPPED
[INFO] plugin e-pipelineInput ............................. SKIPPED
[INFO] plugin t-sparqlSelectMulti ......................... SKIPPED
[INFO] plugin t-filesRenamer .............................. SKIPPED
[INFO] plugin t-templatedXlsToCsv ......................... SKIPPED
[INFO] plugin t-fileHasher ................................ SKIPPED
[INFO] plugin x-virtuosoExtractor ......................... SKIPPED
[INFO] plugin t-valueParser ............................... SKIPPED
[INFO] plugin x-deleteDirectory ........................... SKIPPED
[INFO] plugin x-graphStorePurger .......................... SKIPPED
[INFO] plugin t-htmlCssUv ................................. SKIPPED
[INFO] plugin t-modifyDate ................................ SKIPPED
[INFO] plugin t-geoTools .................................. SKIPPED
[INFO] plugin l-sparqlEndpointChunked ..................... SKIPPED
[INFO] plugin t-bingTranslator ............................ SKIPPED
[INFO] plugin t-chunkedToTurtle ........................... SKIPPED
[INFO] plugin t-streamCompression ......................... SKIPPED
[INFO] plugin t-jsonToJsonLd .............................. SKIPPED
[INFO] plugin t-jsonLdFormat .............................. SKIPPED
[INFO] plugin e-sparqlEndpointList ........................ SKIPPED
[INFO] plugin e-sparqlEndpointChunkedList ................. SKIPPED
[INFO] plugin t-sparqlConstructToFileList ................. SKIPPED
[INFO] plugin c-files ..................................... SKIPPED
[INFO] plugin l-solr ...................................... SKIPPED
[INFO] plugin t-chunkedToFiles ............................ SKIPPED
[INFO] lp-plugins ......................................... SKIPPED
[INFO] lp-deploy-dependencies ............................. SKIPPED
[INFO] lp-frontend ........................................ SKIPPED
[INFO] LinkedPipes ........................................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 10.378 s
[INFO] Finished at: 2017-09-28T13:34:35+00:00
[INFO] Final Memory: 30M/414M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.20.1:test (default-test) on project rdf-utils: There are test failures.
[ERROR]
[ERROR] Please refer to /etl/rdf-utils/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date]-jvmRun[N].dump, [date].dumpstream and [date]-jvmRun[N].dumpstream.
[ERROR] The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was /bin/sh -c cd /etl/rdf-utils && /usr/lib/jvm/java-1.8-openjdk/jre/bin/java -jar /etl/rdf-utils/target/surefire/surefirebooter2706762112386501051.jar /etl/rdf-utils/target/surefire 2017-09-28T13-34-34_222-jvmRun1 surefire8241513072862723067tmp surefire_02852574277917035699tmp
[ERROR] Error occurred in starting fork, check output in log
[ERROR] Process Exit Code: 1
[ERROR] org.apache.maven.surefire.booter.SurefireBooterForkException: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was /bin/sh -c cd /etl/rdf-utils && /usr/lib/jvm/java-1.8-openjdk/jre/bin/java -jar /etl/rdf-utils/target/surefire/surefirebooter2706762112386501051.jar /etl/rdf-utils/target/surefire 2017-09-28T13-34-34_222-jvmRun1 surefire8241513072862723067tmp surefire_02852574277917035699tmp
[ERROR] Error occurred in starting fork, check output in log
[ERROR] Process Exit Code: 1
[ERROR] at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:686)
[ERROR] at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:535)
[ERROR] at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:280)
[ERROR] at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:245)
[ERROR] at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1124)
[ERROR] at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:954)
[ERROR] at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:832)
[ERROR] at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
[ERROR] at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
[ERROR] at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
[ERROR] at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
[ERROR] at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
[ERROR] at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
[ERROR] at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
[ERROR] at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
[ERROR] at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
[ERROR] at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
[ERROR] at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
[ERROR] at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
[ERROR] at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
[ERROR] at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
[ERROR] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR] at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR] at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR] at java.lang.reflect.Method.invoke(Method.java:498)
[ERROR] at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
[ERROR] at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
[ERROR] at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
[ERROR] at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :rdf-utils
ERROR: Service 'linkedpipes_5' failed to build: The command '/bin/sh -c cd /etl && mvn install' returned a non-zero code: 1
 
 
Many thanks in advance,
VonNao

**Comment by skarampatakis** [comment]
I think this is an error from the LinkedPipes build so maybe @jakubklimek could have a look.

**Comment by skarampatakis** [comment]
I can confirm that it happens the same also to me when try to bring up the server with docker-compose.

**Comment by skarampatakis** [comment]
And managed to build it by skipping the tests on maven install.

**Comment by liyakun** [comment]
@VonNao I already updated the docker file to skip the maven tests, it should build without test problems now. BTW, we are going to work on testing the platform replica on our own server, so the documentation may be updated frequently on [README.md](https://github.com/openbudgets/integration/blob/master/README.md).

**Comment by VonNao** [comment]
@liyakun Thank you very much for your help. This time it worked without any problems :)!
