### ISSUE TITLE
Integrated OpenCPU returns different results

### ISSUE THREAD

**Issue by larjohn** [openbudgets/integration#28]
@kleanthisk10 after OpenCPU was integrated, the result of descriptive statistics is different. It does not contain some histogram attributes anymore.

Do you know if it is an issue with some library that is on an older version?

**Comment by skarampatakis** [comment]
Please delete previous image "okgreece/opencpu-docker-obeu" and build again. It seems that the updating function was not working correcty, so some updates are not included.

Also please note that I have made some changes on the proxy configuration removing the second "/ocpu" on the url. So please update DAM and Indigo where needed. I have also included a script to trigger the update. But in any case the docker image for opencpu has to be updated.

**Comment by larjohn** [comment]
Indigo does not store URLs, they are retrieved from DAM. So DAM and the docker stuff should be updated to reflect changes.

**Comment by kleanthisk10** [comment]
@larjohn yes indeed, it's not an issue, that 's the last update of the library, more simple results for histograms!

**Comment by skarampatakis** [comment]
Currently it is not working because the URL is wrong. It adds another /ocpu after the domain name.

**Comment by liyakun** [comment]
@skarampatakis because you changed the setting of Nginx to opencpu docker, anyway, it works now.

**Comment by skarampatakis** [comment]
@liyakun I could not change the configuration on DAM because it was hardcoded on the DAM repo.

**Comment by skarampatakis** [comment]
Can we close this now?
