### ISSUE TITLE
Minimum requirements

### ISSUE THREAD

**Issue by skarampatakis** [openbudgets/integration#29]
What are the minimum system requirements for a complete deployment?

**Comment by liyakun** [comment]
thanks, I added hardware recommendations to the [README.md](https://github.com/openbudgets/integration/blob/master/README.md) file according to the hardware specifications in [OEBU platform](http://apps.openbudgets.eu/). 

For the minimum system requirements, i will check the resource usage on the server.

**Comment by liyakun** [comment]
@skarampatakis I checked the deployment of the docker stack on one ubuntu 16.04 within a virtualbox virtual machine. The system resource useage is as follows:

1. Single Intel i7-7700HQ 2.80GHz CPU core
2. 2.7 GB Memory usage out of 4GB
3. 224 MB Swap usage out of 4Gb
4. 20 GB disk usage out of 97Gb

Of course, those are the usages without performing any operation(except very small browsing) with the softwares deployed on the docker stack. It is obvious that you will certainly need higher configuration than those according to your own needs.
