### ISSUE TITLE
Triplestore empty

### ISSUE THREAD

**Issue by skarampatakis** [openbudgets/integration#3]
Hi @liyakun, 
Are you updating the triplestore? 
It seems to be empty.

http://data.openbudgets.eu/sparql?default-graph-uri=&query=select+distinct+%3Fgraph+where+%7BGRAPH+%3Fgraph+%7B%3Fs+%3Fp+%3Fo%7D%7D&format=text%2Fhtml&timeout=0&debug=on

![image](https://cloud.githubusercontent.com/assets/2419820/26074484/a81d9f40-39ba-11e7-8278-8019c987a4c3.png)

**Comment by liyakun** [comment]
Hi @skarampatakis 
Yes, there is a query problem between rudolf and "virtuoso staging", then I changed it to connect "virtuoso production" to see where the problem happens.

**Comment by skarampatakis** [comment]
Do you want any help on this? When will you revert the change?

**Comment by liyakun** [comment]
@skarampatakis it would be great if you can help, i really appreciate. 
You can see the problem when you access "http://eis-openbudgets.iais.fraunhofer.de/search/package". It seems like a problem of Virtuoso setting. Do you have any idea? 

I will most likely going to revert it tomorrow, as it still has the same problem as using "Virtuoso staging".

@larjohn Do you have any idea about this query problem?

**Comment by skarampatakis** [comment]
It seems to be an unresolved Virtuoso issue, as seen here 
https://github.com/openlink/virtuoso-opensource/issues/371

And

https://github.com/openlink/virtuoso-opensource/issues/118

Perhaps @jakubklimek could provide some info here as well. 

Query recostruction is suggested as a temporal fix. I will look at it tommorow. Possibly some values on the binds.

**Comment by liyakun** [comment]
Okay, thanks. At first, with the "Virtuoso staging" version, it has "Virtuoso 42000 Error The estimated execution time ****** (sec) exceeds the limit of 600 (sec)." Then I comment out the max estimated execution time of the "Virtuoso staging". Afterwards, there is an error regarding to the "number of results" exceeding the limit. I can post more detail tomorrow after switching to the staging version.

**Comment by skarampatakis** [comment]
I have checked the query. It seems that by removing the "group by" it runs. 

@larjohn what is the purpose of grouping on non aggregated data? What do you want to achieve?
```
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX qb: <http://purl.org/linked-data/cube#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX xro: <http://purl.org/xro/ns#>
SELECT DISTINCT ?attribute ?value ?shortName 
WHERE 
{ 
?dsd qb:component ?component .
?dataset a qb:DataSet ;
 qb:structure ?dsd ;
 ?attribute ?value .
?component ?componentProperty ?attribute ;
 qb:componentAttachment qb:DataSet .
?componentProperty rdfs:subPropertyOf qb:componentProperty .

OPTIONAL { ?attribute a ?propertyType . VALUES ?propertyType {qb:CodedProperty qb:MeasureProperty qb:DimensionProperty} } 
FILTER (?name = 'krefeld20152019descriptors1__1934c') 
BIND (REPLACE(str(?attribute), '^.*(#|/)', "") AS ?shortName) 
BIND (CONCAT(REPLACE(str(?dataset), '^.*(#|/)', ""), '__', SUBSTR(MD5(STR(?dataset)),1,5)) AS ?name) } 
#GROUP BY ?attribute ?value ?shortName
```

**Comment by skarampatakis** [comment]
Unless it is used somewhere I would suggest to remove/comment  https://github.com/openbudgets/rudolf/blob/master/app/Model/BabbageModelResult.php#L294

**Comment by liyakun** [comment]
@skarampatakis thanks, I commented the "Group BY" on my forked rudolf repository, now it is working correctly.
