### ISSUE TITLE
Virtuoso staging eats up system resources

### ISSUE THREAD

**Issue by skarampatakis** [openbudgets/integration#31]
Atm virtuoso staging is configured with the 16GB memory configuration. This may lead to system freeze when host is on low specs. I think it should be documented so users could take care before deployment.

**Comment by liyakun** [comment]
@skarampatakis you mean for `MaxQueryMem`, right?

**Comment by liyakun** [comment]
@skarampatakis thank you very much for the report, I already documented this at the [README.md](https://github.com/openbudgets/integration/blob/master/README.md).
