### ISSUE TITLE
Build Error on microsite

### ISSUE THREAD

**Issue by skarampatakis** [openbudgets/integration#33]
Tried to bring up the latest version of the platform and stuck here
```
ERROR: for microsite  Cannot start service microsite: invalid header field value "oci runtime error: container_linux.go:247: starting container process caused \"process_linux.go:359: container init caused \\\"rootfs_linux.go:53: mounting \\\\\\\"/home/dbpedia/NetBeansProjects/integration/volumes/microsite/data/db.sqlite3\\\\\\\" to rootfs \\\\\\\"/var/lib/docker/aufs/mnt/4a7244f385906006002946d15db9ba8866f4e17ab88b14ea5edeb0a58e1839b4\\\\\\\" at \\\\\\\"/var/lib/docker/aufs/mnt/4a7244f385906006002946d15db9ba8866f4e17ab88b14ea5edeb0a58e1839b4/microsite/db.sqlite3\\\\\\\" caused \\\\\\\"not a directory\\\\\\\"\\\"\"\n"
ERROR: Encountered errors while bringing up the project.
```

**Comment by liyakun** [comment]
@skarampatakis thanks a lot for reporting the issues. I think this is because of the shared volumes, I will check.

**Comment by skarampatakis** [comment]
My bad. You are correct. I forgot to run the initVolumes.sh script since it was a build from scratch.
I deleted the volumes folder and run the script and then again the refresh script.
I have now built the platform correctly. Thank you!

**Comment by liyakun** [comment]
@skarampatakis no problem, thank you, it is good that you are able to build the platform correctly.
