### ISSUE TITLE
Microsite: cannot add user

### ISSUE THREAD

**Issue by skarampatakis** [openbudgets/integration#34]
There seems to be an error when try to add a new user through django admin page. Javascript is returned.

https://apps.openbudgets.eu/microsite/admin/auth/user/add/

**Comment by skarampatakis** [comment]
The same does not happen on local deployment. Maybe an interference with nginx conf and OS Admin? I had a similar behavior with the KPIs app where the admin page could not be loaded correctly and instead OS Admin were brought up.

**Comment by liyakun** [comment]
@skarampatakis I don't have the login credential to the admin page, @pierorex could you have a look of this issue?

**Comment by skarampatakis** [comment]
It is on the .env on the integration folder on Fhg. I used it yesterday
and the login works.

Στις 2 Οκτ 2017 10:24, ο χρήστης "Yakun Li" <notifications@github.com>
έγραψε:

**Comment by liyakun** [comment]
@skarampatakis thanks, i tried before with the username and password which did not work for me, tried with email and password, it works, thanks.

**Comment by liyakun** [comment]
@skarampatakis I already removed OS-admin from OBEU docker stack, so it should not be a problem of it. I think maybe some setting in Nginx, but not clear how to fix it still. @hantongliu Could you have a look at this issue when you are available?

**Comment by skarampatakis** [comment]
Why you removed OS admin? Isn't needed for the FDP2RDF pipeline?

**Comment by liyakun** [comment]
@skarampatakis for FDP2RDF pipeline, it uses OS admin hosted on OpenSpending.

**Comment by liyakun** [comment]
@skarampatakis it turns out that the Nginx configuration of Rudolf rewrites this path to one Javascript file.
