### ISSUE TITLE
SQL-Exception when visiting the port 80 application 

### ISSUE THREAD

**Issue by VonNao** [openbudgets/integration#35]
Hello everyone,

after running **refresh_and_restart_prod.sh** script and finnishing all deployments i get the following error when visiting the webpage.

QueryException in Connection.php line 729:
SQLSTATE[HY000]: General error: 1 no such table: resource_classes (SQL: select * from "resource_classes" where "enabled" = 1)

Did i miss something in regard to the databasedeployment?

Thank you very much for your help!

Best regards
VonNao

**Comment by skarampatakis** [comment]
Hello,
Could you please check again and report if there is any issue? There was some migrations missing from the database.
