### ISSUE TITLE
Will the changed regex influence the software?

### ISSUE THREAD

**Issue by liyakun** [openbudgets/integration#37]
https://github.com/openbudgets/integration/blob/1cf1ce7d7e4e8bf38b0a1a7a34431d8b2a1a6f01/docker-config/nginx/conf/includes/locations/okgr_apps.conf#L17

Hi @larjohn , I changed the above regex matching because there is a conflict between the original pattern with the url path of microsite, do you think this will influence the behavior of other softwares? thanks.

**Comment by larjohn** [comment]
If authentication in OS Viewer works, then it shouldn't be an issue

**Comment by liyakun** [comment]
@larjohn thanks, OS Viewer on FHG server works fine, so I assume it has no problem.
