### ISSUE TITLE
Bonn datasets empty visualization 

### ISSUE THREAD

**Issue by fathoni** [openbudgets/integration#4]
Bonn datasets are available in the [explorer ](http://eis-openbudgets.iais.fraunhofer.de/explorer/) but upon exploring this in the [viewer](http://eis-openbudgets.iais.fraunhofer.de/viewer/bonn-budget-2018__f1c5f), there is no data/visualization available. This can be a dataset issue, Rudolf or OS-Viewer. @larjohn , Could you have a look?

**Comment by larjohn** [comment]
Trying the following query


```
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX qb: <http://purl.org/linked-data/cube#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT DISTINCT ?dsd WHERE {
	
         <http://data.openbudgets.eu/resource/dataset/bonn-budget-2018> a qb:DataSet ;
		qb:structure ?dsd .
	?dsd qb:component ?component .

	
}

```

returns an empty resultset, which is the reason it does not work.

**Comment by fathoni** [comment]
The previous feedback has been taken into account. Component properties are now provided but still seems that there are problems with visualization. For example, Bonn dataset 2017 can be seen [here](http://eis-openbudgets.iais.fraunhofer.de/viewer/bonn-budget-2017__c9504?measure=%22amount.sum%22&groups%5B%5D=%22economicClassification.economicClassification%22&order=%22amount.sum%7Cdesc%22&visualizations%5B%5D=%22Treemap%22&lang=en). I suspect that there are some problems with DSD, but I could not see the problem there. Perhaps again @larjohn can have additional look?

**Comment by skarampatakis** [comment]
@fathoni probably related https://github.com/openbudgets/datasets/issues/84

**Comment by fathoni** [comment]
Well, at least there is a [visualization ](http://apps.openbudgets.eu/viewer/bonn-budget-2022__293d8?measure=%22amount.sum%22&groups%5B%5D=%22administrativeClassification.notation%22&series%5B%5D=%22budgetPhase.budgetPhase%22&series%5B%5D=%22fiscalYear.notation%22&series%5B%5D=%22currency.currency%22&order=%22amount.sum%7Cdesc%22&visualizations%5B%5D=%22Radar%22&visualizations%5B%5D=%22Table%22&visualizations%5B%5D=%22BarChart%22&lang=en )for now, though it is limited to a table, radar and bar chart.
