### ISSUE TITLE
refresh_and_restart_prod.sh failling while building damapp

### ISSUE THREAD

**Issue by VonNao** [openbudgets/integration#41]
Hello,

after updating our host-OS we get the following error message while restarting openbudget.

Get:6 http://us.archive.ubuntu.com/ubuntu/ trusty-updates/main python3-tk amd64 3.4.3-1~14.04.2 [23.5 kB]
Err http://us.archive.ubuntu.com/ubuntu/ trusty-updates/main idle-python3.4 all 3.4.3-1ubuntu1~14.04.5
  404  Not Found [IP: 91.189.91.23 80]
Get:7 http://us.archive.ubuntu.com/ubuntu/ trusty/main idle3 all 3.4.0-0ubuntu2 [3080 B]
Err http://security.ubuntu.com/ubuntu/ trusty-security/main idle-python3.4 all 3.4.3-1ubuntu1~14.04.5
  404  Not Found [IP: 91.189.88.149 80]
Fetched 2167 kB in 1s (1692 kB/s)
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/p/python3.4/idle-python3.4_3.4.3-1ubuntu1~14.04.5_all.deb  404  Not Found [IP: 91.189.88.149 80]

E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
make: *** [pre] Error 100
ERROR: Service 'damapp' failed to build: The command '/bin/sh -c yes | make pre &&     source ./env/bin/activate &&     make dam' returned a non-zero code: 2

Is it a problem on Ubuntu's side or something wrong on our side?
Anyone encountered that problem before?

Thanks in advance!

Best regards
Alex

**Comment by liyakun** [comment]
@VonNao sorry for late reply, the problem should have been solved by https://github.com/openbudgets/integration/commit/26365f940d1626fd1a3d1544b2f6c7f2c4ea2fb4
