### ISSUE TITLE
Inconsistent visualization on Viewer

### ISSUE THREAD

**Issue by fathoni** [openbudgets/integration#5]
Both screenshots are from a similar [dataset](http://apps.openbudgets.eu/viewer/bonn-budget-2022-costCenter__ceed0?measure=%22amount.sum%22&groups%5B%5D=%22functionalClassification.notation%22&order=%22amount.sum%7Cdesc%22&visualizations%5B%5D=%22Treemap%22&lang=en), but captured from different browsers:

Firefox:
![image](https://user-images.githubusercontent.com/1597027/28274673-de724996-6b11-11e7-8327-b86c051e8233.png)

Chrome:
![image](https://user-images.githubusercontent.com/1597027/28274737-172a88b6-6b12-11e7-961d-5efc95901db1.png)

I am unsure if this is an issue of dataset, rudolf, or viewer.

This [issue](https://github.com/openbudgets/datasets/issues/85) might be related.

**Comment by larjohn** [comment]
This also appeared on my browsers. It might have to do with some kind of cached file. I ctrl+f5 on the 

http://apps.openbudgets.eu/api/3/cubes/bonn-budget-2022-costCenter__ceed0/aggregate?drilldown=functionalClassification.notation%7CfunctionalClassification.prefLabel&order=amount.sum:desc&pagesize=30

file and the output now seems consistent for me.

**Comment by skarampatakis** [comment]
Just checked on both mentioned browsers and I get the same picture so I think we can close this now. Please reopen if this is not the case.
