### ISSUE TITLE
Virtuoso container fails to install Java 8 JRE

### ISSUE THREAD

**Issue by larjohn** [openbudgets/integration#6]
I tried to build the server in an Ubuntu 16.04.2. The virtuoso container cannot be built because the installation of the JRE depends on the installation of another package which in turn depends on the installation of an old version of cacerts for Java.

I resolved it locally by using ppa:saiarcot895/myppa, as suggested [here ](https://askubuntu.com/questions/464755/how-to-install-openjdk-8-on-14-04-lts#comment1069759_464755).

Another option would be for the docker image to be updated to a newer version (based on Ubuntu 16.x), but this is still a branch in the tenforce repository, and I don't know how to pull a branch in the Dockerfile.

**Comment by liyakun** [comment]
@larjohn thanks for reporting, the base image of the virtuoso container has been changed to ubuntu 16.04.
