### ISSUE TITLE
Labels of hierarchies missing on OS Viewer

### ISSUE THREAD

**Issue by skarampatakis** [openbudgets/integration#9]
![image](https://user-images.githubusercontent.com/2419820/28656046-4bf8e8f6-72a8-11e7-9819-76cde0743ab7.png)

the same happens for filters too as it can be seen.

http://apps.openbudgets.eu/viewer/europe-greece-municipality-thessaloniki-2016-revenue__c40a1?measure=%22amount.sum%22&groups%5B%5D=%22date.date%22&order=%22amount.sum%7Cdesc%22&visualizations%5B%5D=%22Treemap%22&lang=en

**Comment by larjohn** [comment]
This is the expected behaviour, given the results of the following query:

```
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX qb: <http://purl.org/linked-data/cube#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT ?label WHERE {
	<http://data.openbudgets.eu/ontology/dsd/europe-greece-municipality-thessaloniki-2016-revenue/dimension/functional-classification> rdfs:label ?label .
}
```
I will have Rudolf provide the last part of the property URI as a label but this is not a solution. 

@skarampatakis do you happen to know where codelists are loaded? We have missed this one (probably not only this) out...

**Comment by skarampatakis** [comment]
This is a dataset coming from the FDP2RDF pipeline. Codelists are packed along with the dataset and the DSD. So I believe all of them are loaded on the triplestore at the time the dataset gets loaded. The dump of  this dataset can be found [here](http://apps.openbudgets.eu/dumps/fromfdp/europe-greece-municipality-thessaloniki-2016-revenue.nt) where you can confirm the above.

I believe that  the dimensions decared by specific DSDs should have all the mandatory properties and ```rdfs:label``` is one of them. But perhaps this is an issue of the FDP2RDF pipeline. 

In the meantime, I believe the best approach of having a label for each dimension, if originally is absent, would be to use the label of the superproperty that it points. For instance, [this](http://data.openbudgets.eu/ontology/dsd/dimension/functionalClassification) one. The dimension declared on the specific dataset is related with the above mentioned abstract dimension via the ```rdfs:subProperyOf``` property. 

I think this is the approach we should follow also for giving labels to the pipeline generated dimensions, as there is no way to define one through the Packager atm. Perhaps a concatenation of the abstract property label and some dataset specific could pose a good solution.

**Comment by skarampatakis** [comment]
@marek-dudas could you check this?

**Comment by marek-dudas** [comment]
I thought that what @skarampatakis proposes would be followed, i.e., using the label from the parent OBEU property. The pipeline currently does not output labels on dimensions, since at the time it was created, there were no dimension labels in FDP metadata. I can at least add dimension names as labels (i.e., what is now the end part of dimension URI, which comes from the name of the JSON property representing the dimension in FDP) and recheck whether nicer labels could be created at least in some cases.

**Comment by larjohn** [comment]
If the new property is *any* different from the parent OBEU property, why shouldn't it have a label?

It is a single property, a single triple, it is not duplicate data. If it is redudancy to store a label about a _new_ property isn't it redudancy to define a new property at all? Why not use the same parent property if we can't describe how the child is different from the parent?

Disclaimer: we are not talking about the values of the new property, we are talking about the property.

**Comment by marek-dudas** [comment]
I will of course add the labels, there is no reason why not. I am just saying that I can use the dimension names from FDP, which are keys (or property names) in the JSON descriptor and does not look so nice (e.g. like ```administrative-classification```, or there is even ```unknown``` for unspecified dimensions). The result will be the same as using the last part of the property URI. 

I have prepared a new version of the pipeline with such labels. Unless anyone has better idea, we can deploy it.

Titles of columns, which can optionally be specified in packager, would be nicer - but then there would be problems with dimensions consisting of multiple columns.

**Comment by marek-dudas** [comment]
So I updated the pipeline (both on github and FhG server), it should now add labels to dimension properties. Please let me know if you have any comments.

**Comment by skarampatakis** [comment]
Just checked and seems to be fixed now. Thanks!
